"""Add Student model

Revision ID: b7928fc9a4ac
Revises: e8d949d8ef32
Create Date: 2026-08-10 03:49:07.185027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7928fc9a4ac'
down_revision: Union[str, Sequence[str], None] = 'e8d949d8ef32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('parent_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', name='uq_school_student_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_student_grade', 'students', ['grade'], unique=False)
    op.create_index('ix_student_school_id', 'students', ['school_id'], unique=False)
    op.create_index('ix_student_section', 'students', ['section'], unique=False)
    op.create_index('ix_student_status', 'students', ['status'], unique=False)
    op.create_index('ix_student_student_id', 'students', ['student_id'], unique=False)
    op.create_index('ix_student_user_id', 'students', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_user_id', table_name='students')
    op.drop_index('ix_student_student_id', table_name='students')
    op.drop_index('ix_student_status', table_name='students')
    op.drop_index('ix_student_section', table_name='students')
    op.drop_index('ix_student_school_id', table_name='students')
    op.drop_index('ix_student_grade', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
